name: Daily Blinkit Scraper

on:
  # schedule:
  #   # 3:30 PM IST → Convert to UTC (IST is UTC+5:30) → 10:00 AM UTC
  #   - cron: "0 10 * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
             python blinkit.py

      # Optional: Upload output file as an artifact
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: blinkit-scraped-output
          path: "*.xlsx"
